[package]
name = "guilder-client-<exchange>"
version = "0.1.0"
edition = "2021"

[dependencies]
guilder-abstraction = { version = "0.1" }
reqwest = { version = "0.12", features = ["json"] }
futures-core = "0.3"
futures-util = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
