[package]
name = "guilder-client-hyperliquid"
version = "0.1.14"
edition = "2021"
description = "Hyperliquid client for the guilder multi-exchange crypto trading library"
authors = ["Sho Kaneko <kanekoshoyu@gmail.com>"]
repository = "https://github.com/kanekoshoyu/guilder"
license = "MIT"

[dependencies]
# development: path, deployment: version
# guilder-abstraction = { path = "../../abstraction/target/rust" }
guilder-abstraction = "0.1.12"
reqwest = { workspace = true, features = ["json"] }
futures-core.workspace = true
futures-util = "0.3"
serde = { workspace = true }
serde_json.workspace = true
rust_decimal = "1"
alloy-primitives = { version = "0.8", features = ["serde"] }
tokio.workspace = true
tokio-tungstenite = { version = "0.26", features = ["native-tls"] }
async-stream = "0.3"
k256 = { version = "0.13", features = ["ecdsa"] }
sha3 = "0.10"
hex = "0.4"
rmp-serde = "1"
