[package]
name = "guilder-client-binance"
version = "0.1.1"
edition = "2021"
description = "Binance client for the guilder multi-exchange crypto trading library"

[dependencies]
# development: path, deployment: version
guilder-abstraction = "0.1.16"
reqwest.workspace = true
futures-core.workspace = true
futures-util = "0.3"
rust_decimal = "1"
