[package]
name = "guilder-client-binance"
version = "0.1.0"
edition = "2021"

[dependencies]
# development: path, deployment: version
guilder-abstraction = { path = "../../abstraction/target/rust", version = "0.1.1" }
reqwest.workspace = true
